name: Weekly Lottery Automation

on:
  schedule:
    # 매주 월요일 밤 10시에 로또 구매 (UTC 13:00)
    - cron: '0 13 * * 1'
    # 매주 토요일 밤 9시에 당첨 확인 (UTC 12:00)
    - cron: '0 12 * * 6'
  workflow_dispatch:  # 수동 실행 가능

jobs:
  buy-lottery:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 13 * * 1'  # 월요일 작업만 실행
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - run: pip install -r requirements.txt
      
      - name: Buy lottery tickets
        run: make buy
        env:
          LOTTERY_USERNAME: ${{ secrets.LOTTERY_USERNAME }}
          LOTTERY_PASSWORD: ${{ secrets.LOTTERY_PASSWORD }}
          LOTTERY_COUNT: ${{ secrets.LOTTERY_COUNT }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          BUY_WIN720: ${{ secrets.BUY_WIN720 }}

  check-winning:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 12 * * 6'  # 토요일 작업만 실행
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - run: pip install -r requirements.txt
      
      - name: Check winning
        run: make check
        env:
          LOTTERY_USERNAME: ${{ secrets.LOTTERY_USERNAME }}
          LOTTERY_PASSWORD: ${{ secrets.LOTTERY_PASSWORD }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }} 